query buscarCatalogos(
  $busqueda: BuscarCatalogoDto = {}
  $opciones: BuscarOpciones = {}
  $filtro: BuscarCatalogoDto = {}
) {
  buscarCatalogos(busqueda: $busqueda, opciones: $opciones, filtro: $filtro) {
    _id
    _creado
    _modificado
    nombre
  }
}

mutation crearCatalogos(
  $datos: [CrearCatalogoDto!]!
  $opciones: CrearOpciones = {}
) {
  crearCatalogos(datos: $datos, opciones: $opciones) {
    _id
    _creado
    _modificado
    nombre
  }
}

mutation modificarCatalogos(
  $busqueda: BuscarCatalogoDto!
  $datos: ModificarCatalogoDto!
  $opciones: ModificarOpciones = {}
) {
  modificarCatalogos(busqueda: $busqueda, datos: $datos, opciones: $opciones) {
    _id
    _creado
    _modificado
    nombre
  }
}

mutation borrarCatalogos(
  $busqueda: BuscarCatalogoDto!
  $opciones: BorrarOpciones = {}
) {
  borrarCatalogos(busqueda: $busqueda, opciones: $opciones) {
    _id
    _creado
    _modificado
    nombre
  }
}
