query buscarEntidades_almacen(
  $busqueda: BuscarEntidadDto = {}
  $opciones: BuscarOpciones = {}
  $filtro: BuscarEntidadDto = {}
) {
  buscarEntidades(busqueda: $busqueda, opciones: $opciones, filtro: $filtro) {
    almacen {
      _id
      producto {
        _id
        nombre
        puedeVencer
        vencimientoAvisoFuerte
        vencimientoAvisoSuave
        categoria {
          _id
          nombre
        }
        imagen {
          cloudinaryUrl
        }
        medida {
          abreviacion
        }
        variedades {
          _id
          marca {
            _id
            nombre
          }
          inventarioPeriodo
          inventarioAviso
          cantidadAvisoFuerte
          cantidadAvisoSuave
          cantidadMaxPedido
          imagen {
            archivoLocal
            cloudinaryUrl
          }
        }
      }
      lotes {
        _creado
        vencimiento
        cantidad
        marca {
          _id
          nombre
        }
        bloque
      }
    }
  }
}

mutation crearEntidades_almacen(
  $datos: [CrearEntidadDto!]!
  $opciones: CrearOpciones = {}
) {
  crearEntidades(datos: $datos, opciones: $opciones) {
    almacen {
      _id
      producto {
        _id
        nombre
        puedeVencer
        vencimientoAvisoFuerte
        vencimientoAvisoSuave
        categoria {
          _id
          nombre
        }
        imagen {
          cloudinaryUrl
        }
        medida {
          abreviacion
        }
        variedades {
          _id
          marca {
            _id
            nombre
          }
          inventarioPeriodo
          inventarioAviso
          cantidadAvisoFuerte
          cantidadAvisoSuave
          cantidadMaxPedido
          cantidadMaxPedido
          imagen {
            archivoLocal
            cloudinaryUrl
          }
        }
      }
      lotes {
        _creado
        vencimiento
        cantidad
        marca {
          _id
          nombre
        }
        bloque
      }
    }
  }
}

mutation modificarEntidades_almacen(
  $busqueda: BuscarEntidadDto!
  $datos: ModificarEntidadDto!
  $opciones: ModificarOpciones = {}
) {
  modificarEntidades(busqueda: $busqueda, datos: $datos, opciones: $opciones) {
    almacen {
      _id
      producto {
        _id
        nombre
        puedeVencer
        vencimientoAvisoFuerte
        vencimientoAvisoSuave
        categoria {
          _id
          nombre
        }
        imagen {
          cloudinaryUrl
        }
        medida {
          abreviacion
        }
        variedades {
          _id
          marca {
            _id
            nombre
          }
          inventarioPeriodo
          inventarioAviso
          cantidadAvisoFuerte
          cantidadAvisoSuave
          cantidadMaxPedido
          cantidadMaxPedido
          imagen {
            archivoLocal
            cloudinaryUrl
          }
        }
      }
      lotes {
        _creado
        vencimiento
        cantidad
        marca {
          _id
          nombre
        }
        bloque
      }
    }
  }
}

query contarEntidades_almacen(
  $busqueda: BuscarEntidadDto!
  $opciones: ContarOpciones = {}
) {
  contarEntidades(busqueda: $busqueda, opciones: $opciones)
}

mutation borrarEntidades_almacen(
  $busqueda: BuscarEntidadDto!
  $opciones: BorrarOpciones = {}
) {
  borrarEntidades(busqueda: $busqueda, opciones: $opciones) {
    almacen {
      _id
      producto {
        _id
        nombre
        puedeVencer
        vencimientoAvisoFuerte
        vencimientoAvisoSuave
        categoria {
          _id
          nombre
        }
        imagen {
          cloudinaryUrl
        }
        medida {
          abreviacion
        }
        variedades {
          _id
          marca {
            _id
            nombre
          }
          inventarioPeriodo
          inventarioAviso
          cantidadAvisoFuerte
          cantidadAvisoSuave
          cantidadMaxPedido
          cantidadMaxPedido
          imagen {
            archivoLocal
            cloudinaryUrl
          }
        }
      }
      lotes {
        _creado
        vencimiento
        cantidad
        marca {
          _id
          nombre
        }
        bloque
      }
    }
  }
}
