query buscarMedidas(
  $busqueda: BuscarMedidaDto = {}
  $opciones: BuscarOpciones = {}
  $filtro: BuscarMedidaDto = {}
) {
  buscarMedidas(busqueda: $busqueda, opciones: $opciones, filtro: $filtro) {
    _id
    _creado
    _modificado
    nombre
    abreviacion
    tipoEmpaques {
      _id
      nombre
      abreviacion
      cantidad
    }
    imagen {
      cloudinaryUrl
    }
  }
}

mutation crearMedidas(
  $datos: [CrearMedidaDto!]!
  $opciones: CrearOpciones = {}
) {
  crearMedidas(datos: $datos, opciones: $opciones) {
    _id
    _creado
    _modificado
    nombre
    abreviacion
    tipoEmpaques {
      _id
      nombre
      abreviacion
      cantidad
    }
    imagen {
      cloudinaryUrl
    }
  }
}

mutation modificarMedidas(
  $busqueda: BuscarMedidaDto!
  $datos: ModificarMedidaDto!
  $opciones: ModificarOpciones = {}
) {
  modificarMedidas(busqueda: $busqueda, datos: $datos, opciones: $opciones) {
    _id
    _creado
    _modificado
    nombre
    abreviacion
    tipoEmpaques {
      _id
      nombre
      abreviacion
      cantidad
    }
    imagen {
      cloudinaryUrl
    }
  }
}

mutation borrarMedidas(
  $busqueda: BuscarMedidaDto!
  $opciones: BorrarOpciones = {}
) {
  borrarMedidas(busqueda: $busqueda, opciones: $opciones) {
    _id
    _creado
    _modificado
    nombre
    abreviacion
    tipoEmpaques {
      _id
      nombre
      abreviacion
      cantidad
    }
    imagen {
      cloudinaryUrl
    }
  }
}
