query buscarTransacciones(
  $busqueda: BuscarTransaccionDto = {}
  $opciones: BuscarOpciones = {}
  $filtro: BuscarTransaccionDto = {}
) {
  buscarTransacciones(
    busqueda: $busqueda
    opciones: $opciones
    filtro: $filtro
  ) {
    _id
    _creado
    _modificado
    comprador {
      _id
    }
    vendedor {
      _id
    }
    monto
    glosa
    modalidad
    estado
    comentario
    pedidos {
      pedido {
        _id
      }
      total
    }
  }
}

mutation crearTransacciones(
  $datos: [CrearTransaccionDto!]!
  $opciones: CrearOpciones = {}
) {
  crearTransacciones(datos: $datos, opciones: $opciones) {
    _id
    _creado
    _modificado
    comprador {
      _id
    }
    vendedor {
      _id
    }
    monto
    glosa
    modalidad
    comentario
    estado
    pedidos {
      pedido {
        _id
      }
      total
    }
  }
}

mutation modificarTransacciones(
  $busqueda: BuscarTransaccionDto!
  $datos: ModificarTransaccionDto!
  $opciones: ModificarOpciones = {}
) {
  modificarTransacciones(
    busqueda: $busqueda
    datos: $datos
    opciones: $opciones
  ) {
    _id
    _creado
    _modificado
    comprador {
      _id
    }
    vendedor {
      _id
    }
    monto
    glosa
    modalidad
    comentario
    estado
    pedidos {
      pedido {
        _id
      }
      total
    }
  }
}

mutation borrarTransacciones(
  $busqueda: BuscarTransaccionDto!
  $opciones: BorrarOpciones = {}
) {
  borrarTransacciones(busqueda: $busqueda, opciones: $opciones) {
    _id
    _creado
    _modificado
    comprador {
      _id
    }
    vendedor {
      _id
    }
    monto
    glosa
    modalidad
    comentario
    estado
    pedidos {
      pedido {
        _id
      }
      total
    }
  }
}
