export const columnaOfertas = [
  // {
  //   name: 'creado',
  //   label: 'Creado',
  //   align: 'left',
  //   field: (row: any) => row._creado,
  // },
  {
    name: 'imagen',
    label: 'Imagen',
    align: 'left',
    field: (row: any) => row.imagen?.cloudinaryUrl,
  },
  {
    name: 'modificado',
    label: 'Modificado',
    align: 'left',
    field: (row: any) => row._modificado,
    format: (val, row) => `${fechaMes(row._modificado ?? row._creado)}`,
    sortable: true,
  },
  {
    name: 'nombre',
    label: 'Nombre',
    align: 'left',
    field: (row: any) => row.nombre,
    sortable: true,
    slot: true,
  },
  // {
  //   name: 'ingredientes',
  //   required: true,
  //   label: 'Ingredientes',
  //   align: 'left',
  //   slot: true,
  //   field: (row: any) => row.ingredientes,
  // },
  // {
  //   name: 'preparados',
  //   required: true,
  //   label: 'Preparados',
  //   align: 'left',
  //   field: (row: any) => row.preparados.map((p: any) => p),
  //   sortable: true,
  // },
  {
    name: 'catalogo',
    required: true,
    label: 'Catalogo',
    align: 'left',
    field: (row: any) => row.catalogo,
    slot: true,
    sortable: true,
  },
  {
    name: 'precioSinFactura',
    required: true,
    label: 'precio S/F',
    align: 'left',
    field: (row: any) => row.precioSinFactura + 'Bs',
    sortable: true,
  },
  {
    name: 'precioConFactura',
    required: true,
    label: 'precio C/F',
    align: 'left',
    field: (row: any) => row.precioConFactura + 'Bs',
    sortable: true,
  },
  {
    name: 'actions',
    label: 'Acciones',
    align: 'right',
    slot: true,
  },
];
