#
# ENTIDADES : STOCKS, INVENTARIOS, MENUS
#

query buscarEntidades_almacen(
  $busqueda: BuscarEntidadDto = {}
  $opciones: BuscarOpciones = {}
  $filtro: BuscarEntidadDto = {}
) {
  buscarEntidades(busqueda: $busqueda, opciones: $opciones, filtro: $filtro) {
    almacen {
      producto {
        _id
        nombre
      }
      cantidadLimite
      lotes {
        vencimiento
        cantidad
        bloque {
          nombre
        }
      }
    }
  }
}

mutation modificarEntidades_stock(
  $busqueda: BuscarEntidadDto!
  $datos: ModificarEntidadDto!
  $opciones: ModificarOpciones = {}
) {
  modificarEntidades(busqueda: $busqueda, datos: $datos, opciones: $opciones) {
    almacen {
      producto {
        _id
        nombre
      }
      cantidadLimite
      lotes {
        vencimiento
        cantidad
        bloque {
          nombre
        }
      }
    }
  }
}

mutation HacerInventario(
  $busqueda: BuscarEntidadDto!
  $datos: CrearInventarioDto!
  $guardar: Boolean = true
  $opciones: BuscarOpciones = {}
) {
  hacerInventario(
    busqueda: $busqueda
    datos: $datos
    opciones: $opciones
    guardar: $guardar
  ) {
    _id
    producto {
      _id
    }
    reporte
    diferencias {
      vencimiento
      diferencia
    }
    lotes {
      vencimiento
      cantidad
      bloque {
        nombre
      }
    }
  }
}

query productosMenu(
  $busqueda: BuscarEntidadDto!
  $busquedaMenu: BuscarMenuDto!
  $opciones: BuscarOpciones = {}
) {
  entidadProductosMenu(
    busqueda: $busqueda
    busquedaMenu: $busquedaMenu
    opciones: $opciones
  ) {
    _id
    nombre
  }
}

query filaInventario(
  $busqueda: BuscarEntidadDto!
  $opciones: BuscarOpciones = {}
) {
  filaInventario(busqueda: $busqueda, opciones: $opciones) {
    _id
    nombre
  }
}

mutation modificarEntidades_problemas(
  $busqueda: BuscarEntidadDto!
  $datos: ModificarEntidadDto!
  $opciones: ModificarOpciones = {}
) {
  modificarEntidades(busqueda: $busqueda, datos: $datos, opciones: $opciones) {
    problemas {
      _id
      _creado
      inventario {
        _id
      }
      producto {
        _id
        nombre
      }
      diferencias {
        vencimiento
        diferencia
      }
      fechaResolucion
      reporte
      resuelto
    }
  }
}
