#
# AUTENTICACION
#

query conectar($datos: ConexionDto!) {
  conectar(datos: $datos) {
    token
    personaId
    usuario
    nombre
    apellido
    correo
    telefono
    cloudinaryUrl
    entidadId
    entidadNombre
    entidadTipo
    cargos {
      nombre
    }
    permisos
  }
}

query entidadesUsuarioConectado($opciones: BuscarOpciones = {}) {
  entidadesUsuarioConectado(opciones: $opciones) {
    _id
    nombre
    tipo
  }
}

query buscarEntidades_empleadoCargos(
  $busqueda: BuscarEntidadDto = {}
  $opciones: BuscarOpciones = {}
  $filtro: BuscarEntidadDto = {}
) {
  buscarEntidades(busqueda: $busqueda, opciones: $opciones, filtro: $filtro) {
    empleados {
      cargos {
        nombre
      }
    }
  }
}

query buscarEntidades_tipo(
  $busqueda: BuscarEntidadDto = {}
  $opciones: BuscarOpciones = {}
  $filtro: BuscarEntidadDto = {}
) {
  buscarEntidades(busqueda: $busqueda, opciones: $opciones, filtro: $filtro) {
    _id
    nombre
    tipo
  }
}

query pedirRDC($correo: String!) {
  pedirReinicioDeContrasena(correo: $correo)
}

query actuarRDC($token: String!, $contrasena: String!) {
  actuarReinicioDeContrasena(token: $token, contrasena: $contrasena)
}
