# EMPLEADOS
query buscarEntidadEmpleados(
  $busqueda: BuscarEntidadDto!
  $busquedaEmpleado: BuscarEmpleadoDto!
  $opciones: OpcionesDto
) {
  entidadBuscarEmpleado(
    busqueda: $busqueda
    busquedaEmpleado: $busquedaEmpleado
    opciones: $opciones
  ) {
    _id
    persona {
      _id
      nombre
      apellido
      correo
      telefono
    }
    cargo
  }
}

mutation agregarEmpleadoEntidad(
  $busqueda: BuscarEntidadDto!
  $datos: CrearEmpleadoDto!
) {
  entidadCrearEmpleado(
    busqueda: $busqueda
    datos: $datos
    opciones: { populate: true }
  ) {
    _id
    cargo
    persona {
      _id
      nombre
    }
  }
}

mutation borrarEmpleadoEntidad(
  $busqueda: BuscarEntidadDto!
  $busquedaEmpleado: BuscarEmpleadoDto!
) {
  entidadBorrarEmpleado(
    busqueda: $busqueda
    busquedaEmpleado: $busquedaEmpleado
    opciones: {}
  )
}

################ ALMACEN ################
# BUSCAR STOCKS DE UNA ENTIDAD
query buscarStocks($busqueda: BuscarEntidadDto!) {
  entidadBuscar(busqueda: $busqueda, opciones: { populate: true, limit: 0 }) {
    almacen {
      producto {
        _id
        nombre
        presentaciones {
          nombre
          cantidad
        }
      }
      cantidadLimite
      lotes {
        vencimiento
        cantidad
        bloque
      }
    }
  }
}

# modificar cantidadLimite
mutation modificarCantidadLimite(
  $entidadBusqueda: BuscarEntidadDto!
  $productoBusqueda: BuscarProductoDto!
  $datos: ModificarStockDto!
) {
  entidadModificarStock(
    entidadBusqueda: $entidadBusqueda
    productoBusqueda: $productoBusqueda
    datos: $datos
    opciones: { populate: true }
  ) {
    producto {
      _id
      nombre
    }
    cantidadLimite
  }
}

# INVENTARIO
mutation hacerInventario(
  $entidadBusqueda: BuscarEntidadDto!
  $datos: CrearInventarioDto!
  $guardar: Boolean!
) {
  entidadHacerInventario(
    entidadBusqueda: $entidadBusqueda
    datos: $datos
    guardar: $guardar
    opciones: { populate: true }
  ) {
    fecha
    producto {
      _id
      nombre
    }
    reporte
    diferencias {
      vencimiento
      diferencia
    }
    lotes {
      vencimiento
      cantidad
      bloque
      presentacion
      cantidadPresentacion
    }
  }
}
# mutation hacerInventario(
#   $entidadBusqueda: BuscarEntidadDto!
#   $datos: CrearInventarioDto!
#   $guardar: Boolean!
# ) {
#   entidadHacerInventario(
#     entidadBusqueda: $entidadBusqueda
#     datos: $datos
#     guardar: $guardar
#     opciones: { populate: true }
#   ) {
#     fecha
#     producto {
#       _id
#       nombre
#     }
#     reporte
#     diferencias {
#       vencimiento
#       diferencia
#     }
#     lotes {
#       vencimiento
#       cantidad
#       bloque
#       presentacion
#       cantidadPresentacion
#     }
#   }
# }

# LISTA DE PROBLEMAS DE INVENTARIO
query ListarProblemas(
  $entidadBusqueda: BuscarEntidadDto!
  $problemaBusqueda: BuscarProblemaDto!
) {
  entidadListarProblemas(
    entidadBusqueda: $entidadBusqueda
    problemaBusqueda: $problemaBusqueda
    opciones: { populate: true }
  ) {
    _id
    inventario {
      _id
    }
    producto {
      _id
      nombre
    }
    diferencias {
      vencimiento
      diferencia
    }
    fechaAparicion
    fechaResolucion
    reporte
    resuelto
  }
}
# query ListarProblemas(
#   $entidadBusqueda: BuscarEntidadDto!
#   $problemaBusqueda: BuscarProblemaDto!
# ) {
#   entidadListarProblemas(
#     entidadBusqueda: $entidadBusqueda
#     problemaBusqueda: $problemaBusqueda
#     opciones: { populate: true }
#   ) {
#     _id
#     inventario {
#       _id
#     }
#     producto {
#       _id
#       nombre
#     }
#     diferencias {
#       vencimiento
#       diferencia
#     }
#     fechaAparicion
#     fechaResolucion
#     reporte
#     resuelto
#   }
# }

# RESOLVER PROBLEMA
mutation ResolverProblema(
  $entidadBusqueda: BuscarEntidadDto!
  $problemaBusqueda: BuscarProblemaDto!
  $datos: ResolverProblemaDto!
) {
  entidadResolverProblema(
    entidadBusqueda: $entidadBusqueda
    problemaBusqueda: $problemaBusqueda
    datos: $datos
    opciones: { populate: true }
  ) {
    _id
    inventario {
      _id
    }
    producto {
      _id
      nombre
    }
    diferencias {
      vencimiento
      diferencia
    }
    fechaAparicion
    fechaResolucion
    reporte
    resuelto
  }
}

# LISTA INVENTARIO DE CATALOGO
query InventarioProductosMenu(
  $busqueda: BuscarEntidadDto!
  $busquedaMenu: BuscarMenuDto!
) {
  entidadProductosMenu(
    busqueda: $busqueda
    busquedaMenu: $busquedaMenu
    opciones: { populate: false }
  ) {
    _id
    nombre
  }
}

# LISTA DE PRODUCTOS INVENTARIAR
query productosInventariar($entidadBusqueda: BuscarEntidadDto!) {
  produccionBuscarProductosNuevos(
    entidadBusqueda: $entidadBusqueda
    opciones: {}
  ) {
    nombre
    _id
  }
}

# AGREGAR ROL EMPLEADO
mutation entidadAsignarRoles(
  $entidadBusqueda: BuscarEntidadDto!
  $datos: [AsignacionRolDto!]!
) {
  entidadAsignarRoles(
    entidadBusqueda: $entidadBusqueda
    datos: $datos
    opciones: { populate: true }
  ) {
    _id
    nombre
    roles {
      persona {
        nombre
      }
      rol
      vencimiento
    }
  }
}
