#
# ENTIDADES
#

query buscarEntidades_problemas(
  $busqueda: BuscarEntidadDto!
  $filtro: BuscarEntidadDto = {}
  $opciones: BuscarOpciones = {}
) {
  buscarEntidades(busqueda: $busqueda, opciones: $opciones, filtro: $filtro) {
    problemas {
      _id
      _creado
      inventario {
        _id
      }
      producto {
        _id
        nombre
      }
      diferencias {
        vencimiento
        diferencia
      }
      fechaResolucion
      reporte
      resuelto
    }
  }
}

# BUSCAR ENTIDADES TIPO PROVEEDOR
query buscarEntidadesProveedor(
  $busqueda: BuscarEntidadDto = {}
  $opciones: BuscarOpciones = {}
  $filtro: BuscarEntidadDto = {}
) {
  buscarEntidades(busqueda: $busqueda, opciones: $opciones, filtro: $filtro) {
    _id
    nombre
    tipo
  }
}

# CREAR UNA ENTIDAD PROVEEDOR
mutation crearEntidadProveedor(
  $datos: [CrearEntidadDto!]!
  $opciones: CrearOpciones = {}
) {
  crearEntidades(datos: $datos, opciones: $opciones) {
    _id
    nombre
    tipo
  }
}
