# CRUD MEDIDAS

query buscarMedidas(
  $busqueda: BuscarMedidaDto = {}
  $opciones: BuscarOpciones = {}
  $filtro: BuscarMedidaDto = {}
) {
  buscarMedidas(busqueda: $busqueda, opciones: $opciones, filtro: $filtro) {
    _id
    nombre
    tipoEmpaques {
      nombre
      abreviacion
    }
  }
}

mutation crearMedidas(
  $datos: [CrearMedidaDto!]!
  $opciones: CrearOpciones = {}
) {
  crearMedidas(datos: $datos, opciones: $opciones) {
    _id
    nombre
  }
}

mutation modificarMedidas(
  $busqueda: BuscarMedidaDto!
  $datos: ModificarMedidaDto!
  $opciones: ModificarOpciones = {}
) {
  modificarMedidas(busqueda: $busqueda, datos: $datos, opciones: $opciones) {
    _id
    nombre
    tipoEmpaques {
      _id
      nombre
      abreviacion
    }
  }
}
