#
# ENTIDAD .MENUS y CATALOGOS
#

query buscarEntidades_menus(
  $busqueda: BuscarEntidadDto = {}
  $opciones: BuscarOpciones = {}
  $filtro: BuscarEntidadDto = {}
) {
  buscarEntidades(busqueda: $busqueda, opciones: $opciones, filtro: $filtro) {
    menus {
      _id
      catalogo {
        _id
        nombre
      }
      exepciones {
        _id
        nombre
      }
    }
  }
}

mutation modificarEntidades_menus(
  $busqueda: BuscarEntidadDto!
  $datos: ModificarEntidadDto!
  $opciones: ModificarOpciones = {}
) {
  modificarEntidades(busqueda: $busqueda, datos: $datos, opciones: $opciones) {
    menus {
      _id
      catalogo {
        _id
        nombre
      }
      exepciones {
        _id
        nombre
      }
    }
  }
}

query entidadLeerMenu(
  $busqueda: BuscarEntidadDto!
  $busquedaMenu: BuscarMenuDto!
  $opciones: BuscarOpciones = {}
) {
  entidadLeerMenu(
    busqueda: $busqueda
    busquedaMenu: $busquedaMenu
    opciones: $opciones
  ) {
    _id
    nombre
    hijas {
      _id
      nombre
      ofertas {
        nombre
      }
      hijas {
        _id
        nombre
        ofertas {
          _id
          nombre
        }
      }
    }
    ofertas {
      _id
      nombre
      ingredientes {
        _id
      }
    }
  }
}
