# CRUD OFERTA
#  BUSCAR
query ofertaBuscar($busqueda: BuscarOfertaDto!) {
  ofertaBuscar(busqueda: $busqueda, opciones: { populate: true, limit: 0 }) {
    _id
    _creado
    nombre
    descripcion
    precio
    grupos
    ocultar
    ingredientes {
      ... on IngredienteProducto {
        _id
        _tipo
        producto {
          _id
          nombre
        }
        cantidad
      }
      ... on IngredienteEleccion {
        _id
        _tipo
        nombre
        cantidadMin
        cantidadMax
        costoAdicional
        items {
          producto {
            _id
            nombre
          }
          cantidad
          costoAdicional
        }
      }
    }
    preparados {
      producto {
        _id
      }
      cantidad
    }
    condiciones {
      ... on CondicionMontoMinimo {
        _id
        _tipo
        montoMinimo
      }
      ... on CondicionPorFechas {
        _id
        _tipo
        fechaInicio
        fechaFin
      }
      ... on CondicionPorDias {
        _id
        _tipo
        dias
      }
      ... on CondicionPorHorarios {
        _id
        _tipo
        horarioInicio
        horarioFin
      }
    }
  }
}
# CREAR
mutation crearOferta($datos: CrearOfertaDto!) {
  ofertaCrear(datos: $datos) {
    _id
    nombre
    descripcion
    precio
    grupos
  }
}
# EDITAR
mutation modificarOfertas(
  $busqueda: BuscarOfertaDto!
  $datos: ModificarOfertaDto!
) {
  ofertaModificar(busqueda: $busqueda, datos: $datos, opciones: { limit: 0 }) {
    _id
    nombre
    descripcion
  }
}
# BORRAR
mutation borrarOfertas($busqueda: BuscarOfertaDto!) {
  ofertaBorrar(busqueda: $busqueda, opciones: { limit: 0 })
}

mutation crearIngredienteProducto(
  $busqueda: BuscarOfertaDto!
  $datos: CrearIngredienteProductoDto!
) {
  ofertaCrearIngredienteProducto(
    busqueda: $busqueda
    datos: $datos
    opciones: { populate: true }
  ) {
    ... on IngredienteProducto {
      _id
      _tipo
      producto {
        nombre
      }
      cantidad
    }
  }
}
mutation editarIngredienteProducto(
  $busqueda: BuscarOfertaDto!
  $datos: ModificarIngredienteProductoDto!
  $busquedaIngrediente: BuscarIngredienteDto!
) {
  ofertaModificarIngredienteProducto(
    busqueda: $busqueda
    datos: $datos
    busquedaIngrediente: $busquedaIngrediente
    opciones: { populate: true }
  ) {
    _id
    _tipo
    producto {
      nombre
    }
    cantidad
  }
}

# BUSCAR PRODUCTO CON SUS PRESENTACIONES PARA AGREGAR PRODUCTO FIJO A OFERTA
query ofertaProductoBuscar($busqueda: BuscarProductoDto!) {
  productoBuscar(busqueda: $busqueda, opciones: { limit: 0 }) {
    _id
    nombre
    presentacionBasica
    presentaciones {
      cantidad
      nombre
    }
  }
}

# CATALOGOS
query buscarCatalogos($busqueda: BuscarCatalogoDto!) {
  catalogoArbol(busqueda: $busqueda, opciones: { populate: true }) {
    _id
    nombre
    ofertas {
      nombre
    }
    hijas {
      _id
      nombre
      ofertas {
        nombre
      }
      hijas {
        _id
        nombre
        ofertas {
          _id
          nombre
        }
        hijas {
          _id
          nombre
          ofertas {
            nombre
          }
        }
      }
    }
  }
}

# query buscarCatalogoID($busqueda: BuscarCatalogoDto!) {
#   catalogoArbol(busqueda: $busqueda, opciones: { populate: true }) {
#     _id
#     nombre
#     ofertas {
#       nombre
#     }
#     hijas {
#       _id
#       nombre
#       ofertas {
#         nombre
#       }
#       hijas {
#         _id
#         nombre
#         ofertas {
#           nombre
#         }
#       }
#     }
#   }
# }

mutation crearCatalogo($datos: CrearCatalogoDto!) {
  catalogoCrear(datos: $datos, opciones: { populate: true }) {
    _id
    nombre
    pariente {
      nombre
    }
    ofertas {
      nombre
    }
  }
}
# MENU - CATALOGO
query puntoLeerCatalogo(
  $busqueda: BuscarEntidadDto!
  $busquedaMenu: BuscarMenuDto!
) {
  entidadLeerMenu(
    busqueda: $busqueda
    busquedaMenu: $busquedaMenu
    opciones: { populate: true }
  ) {
    _id
    nombre
    hijas {
      _id
      nombre
      ofertas {
        nombre
      }
      hijas {
        _id
        nombre
        ofertas {
          _id
          nombre
        }
      }
    }
    ofertas {
      _id
      nombre
      ingredientes {
        ... on IngredienteProducto {
          _id
        }
        ... on IngredienteEleccion {
          cantidadMax
        }
      }
    }
  }
}
