#
# OFERTAS
#

query buscarOfertas(
  $busqueda: BuscarOfertaDto = {}
  $opciones: BuscarOpciones = {}
  $filtro: BuscarOfertaDto = {}
) {
  buscarOfertas(busqueda: $busqueda, opciones: $opciones, filtro: $filtro) {
    _id
    _creado
    nombre
    abreviacion
    descripcion
    catalogo {
      _id
      nombre
    }
    precio
    preparados {
      producto {
        _id
      }
      cantidad
    }
    ingredientes {
      tipo
      producto {
        _id
        nombre
        presentacionBasica
      }
      cantidad
    }
    imagen {
      cloudinaryUrl
    }
  }
}

mutation crearOfertas(
  $datos: [CrearOfertaDto!]!
  $opciones: CrearOpciones = {}
) {
  crearOfertas(datos: $datos, opciones: $opciones) {
    _id
    nombre
    abreviacion
    descripcion
    precio
    catalogo {
      _id
      nombre
    }
    imagen {
      cloudinaryUrl
    }
  }
}

mutation modificarOfertas(
  $busqueda: BuscarOfertaDto!
  $datos: ModificarOfertaDto!
  $opciones: ModificarOpciones = {}
) {
  modificarOfertas(busqueda: $busqueda, datos: $datos, opciones: $opciones) {
    _id
    nombre
    descripcion
    abreviacion
    imagen {
      cloudinaryUrl
    }
  }
}

mutation borrarOfertas(
  $busqueda: BuscarOfertaDto!
  $opciones: BorrarOpciones = {}
) {
  borrarOfertas(busqueda: $busqueda, opciones: $opciones) {
    _id
    nombre
  }
}

query buscarProductos_oferta(
  $busqueda: BuscarProductoDto = {}
  $opciones: BuscarOpciones = {}
  $filtro: BuscarProductoDto = {}
) {
  buscarProductos(busqueda: $busqueda, opciones: $opciones, filtro: $filtro) {
    _id
    nombre
    presentacionBasica
    presentaciones {
      cantidad
      nombre
    }
  }
}

query catalogoArbol(
  $busqueda: BuscarCatalogoDto!
  $opciones: BuscarOpciones = {}
) {
  catalogoArbol(busqueda: $busqueda, opciones: $opciones) {
    _id
    nombre
    ofertas {
      nombre
    }
    hijas {
      _id
      nombre
      ofertas {
        nombre
      }
      hijas {
        _id
        nombre
        ofertas {
          _id
          nombre
        }
        hijas {
          _id
          nombre
          ofertas {
            nombre
          }
        }
      }
    }
  }
}

query catalogoArbol2(
  $busqueda: BuscarCatalogoDto!
  $opciones: BuscarOpciones = {}
) {
  catalogoArbol(busqueda: $busqueda, opciones: $opciones) {
    _id
    nombre
    hijas {
      _id
      nombre
    }
  }
}

mutation crearCatalogos(
  $datos: [CrearCatalogoDto!]!
  $opciones: CrearOpciones = {}
) {
  crearCatalogos(datos: $datos, opciones: $opciones) {
    _id
    nombre
    pariente {
      nombre
    }
    ofertas {
      nombre
    }
  }
}

query catalogoOfertasRecursivo(
  $busqueda: BuscarCatalogoDto!
  $opciones: BuscarOpciones = {}
) {
  catalogoOfertasRecursivo(busqueda: $busqueda, opciones: $opciones) {
    _id
    _creado
    _modificado
    nombre
    abreviacion
    descripcion
    catalogo {
      _id
      nombre
    }
    precio
    preparados {
      producto {
        _id
      }
      cantidad
    }
    ingredientes {
      _id
      tipo
      producto {
        _id
        nombre
        presentacionBasica
      }
      cantidad
    }
    imagen {
      cloudinaryUrl
    }
  }
}
