# INICIAR PEDIDO (PUNTO)
mutation pedidoIniciar($datos: CrearPedidoDto!) {
  pedidoIniciar(datos: $datos) {
    _id
    comprador {
      _id
    }
    vendedor {
      _id
    }
    estado {
      estado
    }
    items {
      oferta {
        _id
      }
      cantidad
    }
  }
}

# CONFIRMAR PEDIDO (PUNTO)
mutation pedidoConfirmarItems($busqueda: BuscarPedidoDto!, $itemIds: [ID!]!) {
  pedidoConfirmarItems(busqueda: $busqueda, itemIds: $itemIds) {
    _id
    estado {
      estado
    }
    items {
      _id
    }
  }
}

# BUSCAR PEDIDOS
query pedidoBuscar($busqueda: BuscarPedidoDto!) {
  pedidoBuscar(
    busqueda: $busqueda
    opciones: { limit: 0, populate: true, populateRecursivo: true }
  ) {
    _id
    _creado
    comprador {
      nombre
      _id
      ruta
      orden
    }
    vendedor {
      nombre
      _id
      ruta
      orden
    }
    estado {
      estado
      fecha
      persona {
        nombre
        apellido
        telefono
      }
    }
    items {
      _id
      oferta {
        nombre
        _id
        ingredientes {
          ... on IngredienteProducto {
            _tipo
            producto {
              nombre
            }
            cantidad
          }
        }
        precio
      }
      cantidad
      estado {
        fecha
        estado
        valor
        comentario
      }
    }
  }
}

# LEER ESTADO
query pedidoLeerEstado($busqueda: BuscarPedidoDto!) {
  pedidoLeerEstado(busqueda: $busqueda)
}

# ACEPTAR ITEMS PEDIDO (CATHERING)
mutation pedidoAceptarItems($busqueda: BuscarPedidoDto!, $itemIds: [ID!]!) {
  pedidoAceptarItems(busqueda: $busqueda, itemIds: $itemIds) {
    _id
    estado {
      estado
    }
    items {
      _id
    }
  }
}

# AJUSTAR ITEMS PEDIDO (CATHERING)
mutation pedidoAjustarItem(
  $busqueda: BuscarPedidoDto!
  $itemId: ID!
  $nuevaCantidad: Float!
  $comentario: String!
) {
  pedidoAjustarItem(
    busqueda: $busqueda
    itemId: $itemId
    nuevaCantidad: $nuevaCantidad
    comentario: $comentario
  ) {
    _id
    estado {
      estado
    }
    items {
      _id
      cantidad
    }
  }
}

# PREPARAR ITEMS PEDIDO (CATHERING)
mutation pedidoPrepararItems($busqueda: BuscarPedidoDto!, $itemIds: [ID!]!) {
  pedidoPrepararItems(busqueda: $busqueda, itemIds: $itemIds) {
    _id
    estado {
      estado
    }
    items {
      _id
    }
  }
}

# RECIBIR ITEMS PEDIDO (PUNTO)
mutation pedidoRecibirItems($busqueda: BuscarPedidoDto!, $itemIds: [ID!]!) {
  pedidoRecibirItems(busqueda: $busqueda, itemIds: $itemIds) {
    _id
    estado {
      estado
    }
    items {
      _id
    }
  }
}

query pedidoItemsEstado($busqueda: BuscarPedidoDto!) {
  pedidoBuscar(busqueda: $busqueda, opciones: { limit: 0, populate: true }) {
    _id
    items {
      _id
      oferta {
        nombre
      }
      cantidad
      estado {
        estado
        comentario
        valor
      }
    }
  }
}

# Buscar items de todos los pedidos
query pedidosBuscarItems($busqueda: BuscarPedidoDto!) {
  pedidoBuscar(busqueda: $busqueda, opciones: { limit: 0, populate: true }) {
    _id
    items {
      _id
      oferta {
        nombre
        precio
        grupos
      }
      cantidad
      estado {
        estado
      }
    }
  }
}

# PEDIDO ACEPTAR TODAS OFERTAS SOLICITABLES
mutation pedidosAceptarOfertasSolicitables($busqueda: BuscarPedidoDto!) {
  pedidosAceptarOfertasSolicitables(busqueda: $busqueda) {
    _id
    estado {
      estado
    }
    comprador {
      _id
      nombre
      ruta
      orden
    }
    items {
      _id
      cantidad
      # TRAER OFERTA MAS POPULATE TRUE
      oferta {
        _id
        nombre
        ingredientes {
          ... on IngredienteProducto {
            _id
            _tipo
            producto {
              _id
              nombre
            }
            cantidad
          }
        }
      }
      estado {
        estado
        fecha
      }
    }
  }
}

# PEDIDO ACEPTAR TODAS OFERTAS DIRECTAS
mutation pedidosAceptarOfertasDirectas($busqueda: BuscarPedidoDto!) {
  pedidosAceptarOfertasDirectas(busqueda: $busqueda) {
    _id
    estado {
      estado
    }
    comprador {
      _id
      nombre
      ruta
      orden
    }
    items {
      _id
      cantidad
      # TRAER OFERTA MAS POPULATE TRUE
      oferta {
        _id
        nombre
        ingredientes {
          ... on IngredienteProducto {
            _id
            _tipo
            producto {
              _id
              nombre
            }
            cantidad
          }
        }
      }
      estado {
        estado
        fecha
      }
    }
  }
}

# PEDIDO OFERTA PREPARADA
mutation pedidosPrepararOfertas(
  $busqueda: BuscarPedidoDto!
  $ofertaIds: [ID!]!
) {
  pedidosPrepararOfertas(busqueda: $busqueda, ofertaIds: $ofertaIds) {
    _id
    estado {
      estado
    }
    items {
      _id
      oferta {
        _id
        nombre
      }
      estado {
        estado
        fecha
      }
    }
  }
}

# PEDIDO OFERTA AJUSTAR
mutation pedidosAjustarOferta(
  $busqueda: BuscarPedidoDto!
  $ofertaId: ID!
  $diferenciaTotal: Float!
  $comentario: String!
) {
  pedidosAjustarOferta(
    busqueda: $busqueda
    ofertaId: $ofertaId
    diferenciaTotal: $diferenciaTotal
    comentario: $comentario
  ) {
    _id
    comprador {
      _id
      nombre
    }
    items {
      oferta {
        _id
        nombre
      }
      cantidad
      estado {
        estado
        valor
        fecha
      }
    }
  }
}
