# INICIAR PEDIDO (PUNTO)
mutation pedidoIniciar($datos: CrearPedidoDto!) {
  pedidoIniciar(datos: $datos) {
    _id
    comprador {
      _id
    }
    vendedor {
      _id
    }
    estado {
      estado
    }
    items {
      oferta {
        _id
      }
      cantidad
    }
  }
}

# BUSCAR PEDIDOS
query pedidoBuscar($busqueda: BuscarPedidoDto!) {
  pedidoBuscar(busqueda: $busqueda, opciones: { limit: 0, populate: true }) {
    _id
    comprador {
      nombre
      _id
    }
    vendedor {
      nombre
      _id
    }
    estado {
      estado
      fecha
      persona {
        nombre
        apellido
        telefono
      }
      entidad {
        nombre
      }
    }
    items {
      oferta {
        nombre
        precio
      }
      cantidad
    }
  }
}
