#
# PERSONAS
#

query buscarPersonas(
  $busqueda: BuscarPersonaDto = {}
  $opciones: BuscarOpciones = {}
  $filtro: BuscarPersonaDto = {}
) {
  buscarPersonas(busqueda: $busqueda, opciones: $opciones, filtro: $filtro) {
    _id
    nombre
    apellido
    correo
    telefono
    apellido
    imagen {
      cloudinaryUrl
    }
  }
}

mutation modificarPersonas(
  $busqueda: BuscarPersonaDto!
  $datos: ModificarPersonaDto!
  $opciones: ModificarOpciones = {}
) {
  modificarPersonas(busqueda: $busqueda, datos: $datos, opciones: $opciones) {
    _id
    nombre
    apellido
    correo
    telefono
    apellido
    imagen {
      cloudinaryUrl
    }
  }
}

mutation crearPersonas(
  $datos: [CrearPersonaDto!]!
  $opciones: CrearOpciones = {}
) {
  crearPersonas(datos: $datos, opciones: $opciones) {
    _id
    _creado
    contrasena
    nombre
    apellido
    telefono
    correo
    usuario
    imagen {
      cloudinaryUrl
    }
  }
}
