mutation crearPersona($datos: CrearPersonaDto!) {
  personaCrear(datos: $datos) {
    _id
    _creado
    contrasena
    nombre
    telefono
    correo
    usuario
  }
}

query buscarPersonas($busqueda: BuscarPersonaDto!) {
  personaBuscar(busqueda: $busqueda, opciones: { limit: 0 }) {
    _id
    nombre
    telefono
    correo
  }
}

mutation modificarPersona(
  $busqueda: BuscarPersonaDto!
  $datos: ModificarPersonaDto!
) {
  personaModificar(busqueda: $busqueda, datos: $datos, opciones: { limit: 0 }) {
    _id
    nombre
    correo
    telefono
  }
}

query buscarPersona($busqueda: BuscarPersonaDto!, $opciones: OpcionesDto) {
  personaBuscar(busqueda: $busqueda, opciones: $opciones) {
    _id
    nombre
    correo
    telefono
    apellido
    imagen
  }
}
