#
# PRODUCTOS
#

query buscarProductos(
  $busqueda: BuscarProductoDto = {}
  $opciones: BuscarOpciones = {}
  $filtro: BuscarProductoDto = {}
) {
  buscarProductos(busqueda: $busqueda, opciones: $opciones, filtro: $filtro) {
    _id
    _creado
    _modificado
    nombre
    comentario
    variedades {
      _id
      marca {
        _id
        nombre
      }
      cantidadMin
      cantidadMax
      imagen {
        archivoLocal
        cloudinaryUrl
      }
    }
    medida {
      nombre
    }
    empaques {
      nombre
      abreviacion
      marca {
        _id
        nombre
      }
      cantidad
    }
    categoria {
      _id
      nombre
    }
    imagen {
      cloudinaryUrl
    }
  }
}

mutation crearProductos(
  $datos: [CrearProductoDto!]!
  $opciones: CrearOpciones = {}
) {
  crearProductos(datos: $datos, opciones: $opciones) {
    _id
    nombre
    comentario
    categoria {
      _id
      nombre
    }
    imagen {
      cloudinaryUrl
    }
  }
}

mutation modificarProductos(
  $busqueda: BuscarProductoDto!
  $datos: ModificarProductoDto!
  $opciones: ModificarOpciones = {}
) {
  modificarProductos(busqueda: $busqueda, datos: $datos, opciones: $opciones) {
    _id
    nombre
    comentario
    categoria {
      nombre
    }
    imagen {
      cloudinaryUrl
    }
  }
}

mutation modificarProductos_categoria(
  $busqueda: BuscarProductoDto!
  $datos: ModificarProductoDto!
  $opciones: ModificarOpciones = {}
) {
  modificarProductos(busqueda: $busqueda, datos: $datos, opciones: $opciones) {
    categoria {
      nombre
      _id
      pariente {
        _id
        nombre
        pariente {
          _id
          nombre
          pariente {
            _id
            nombre
          }
        }
      }
    }
  }
}

mutation borrarProductos(
  $busqueda: BuscarProductoDto!
  $opciones: BorrarOpciones = {}
) {
  borrarProductos(busqueda: $busqueda, opciones: $opciones) {
    _id
    nombre
  }
}

query categoriaArbol(
  $busqueda: BuscarCategoriaDto!
  $opciones: BuscarOpciones = {}
) {
  categoriaArbol(busqueda: $busqueda, opciones: $opciones) {
    _id
    nombre
    # productos {
    #   nombre
    # }
    hijas {
      _id
      nombre
      # productos {
      #   _id
      #   nombre
      # }
      hijas {
        _id
        nombre
        # productos {
        #   _id
        #   nombre
        # }
      }
    }
  }
}

mutation crearCategorias(
  $datos: [CrearCategoriaDto!]!
  $opciones: CrearOpciones = {}
) {
  crearCategorias(datos: $datos, opciones: $opciones) {
    _id
    nombre
    pariente {
      nombre
    }
  }
}

# NUEVO
mutation crearProductosBasicos(
  $datos: [CrearProductoDto!]!
  $opciones: CrearOpciones = {}
) {
  crearProductos(datos: $datos, opciones: $opciones) {
    _id
    nombre
    comentario
    imagen {
      archivoLocal
      cloudinaryUrl
    }
    categoria {
      _id
    }
  }
}

mutation modificarProductosBasicos(
  $busqueda: BuscarProductoDto!
  $datos: ModificarProductoDto!
  $opciones: ModificarOpciones = {}
) {
  modificarProductos(busqueda: $busqueda, datos: $datos, opciones: $opciones) {
    _id
    nombre
    comentario
    imagen {
      archivoLocal
      cloudinaryUrl
    }
    categoria {
      _id
      nombre
    }
  }
}

mutation modificarProductosMarca(
  $busqueda: BuscarProductoDto!
  $datos: ModificarProductoDto!
  $opciones: ModificarOpciones = {}
) {
  modificarProductos(busqueda: $busqueda, datos: $datos, opciones: $opciones) {
    _id
    nombre
    variedades {
      marca {
        _id
      }
      cantidadMin
      cantidadMax
      imagen {
        archivoLocal
        cloudinaryUrl
      }
    }
  }
}

mutation modificarProductosMedidaEmpaque(
  $busqueda: BuscarProductoDto!
  $datos: ModificarProductoDto!
  $opciones: ModificarOpciones = {}
) {
  modificarProductos(busqueda: $busqueda, datos: $datos, opciones: $opciones) {
    _id
    nombre
    medida {
      _id
      nombre
    }
    empaques {
      _id
      nombre
      abreviacion
      marca {
        _id
      }
      cantidad
    }
  }
}
