query conectar($data: ConexionDto!) {
  conectar(data: $data) {
    token
    persona {
      nombre
    }
  }
}

query buscarEntidadesConUsuario {
  buscarEntidadesConUsuario {
    nombre
    _id
    tipo
  }
}
