query categoriaArbol($busqueda: BuscarCategoriaDto!) {
  categoriaArbol(busqueda: $busqueda, opciones: { populate: true }) {
    _id
    nombre
    productos {
      nombre
    }
    hijas {
      _id
      nombre
      productos {
        _id
        nombre
      }
      hijas {
        _id
        nombre
        productos {
          _id
          nombre
        }
      }
    }
  }
}

mutation crearCategoria($datos: CrearCategoriaDto!) {
  categoriaCrear(datos: $datos, opciones: { populate: true }) {
    _id
    nombre
    pariente {
      nombre
    }
  }
}
