# EMPLEADOS
query buscarEntidadEmpleados($busqueda: BuscarEntidadDto!) {
  buscarEntidad(busqueda: $busqueda, options: { populateEmpleados: true }) {
    empleados {
      personaId {
        _id
        nombre
        telefono
        correo
      }
      cargo
    }
    roles {
      personaId
      rol
      vencimiento
    }
    permisos {
      personaId
      permiso
      otorgado
      vencimiento
    }
  }
}

mutation agregarEmpleadoEntidad(
  $entidadId: String!
  $personaId: String!
  $datos: AgregarEmpleadoParcialDto!
) {
  agregarEmpleado(entidadId: $entidadId, personaId: $personaId, datos: $datos) {
    personaId {
      _id
      nombre
      correo
      telefono
    }
    cargo
  }
}

mutation borrarEmpleadoEntidad($entidadId: String!, $personaId: String!) {
  borrarEmpleado(entidadId: $entidadId, personaId: $personaId)
}
