# EMPLEADOS
query buscarEntidadEmpleados($busqueda: BuscarEntidadDto!) {
  entidadBuscar(
    busqueda: $busqueda
    opciones: { populate: ["empleados"], limit: 0 }
  ) {
    _id
    nombre
    empleados {
      _id
      cargo
      persona {
        nombre
        correo
        telefono
      }
    }
  }
}

# Error al poner nombre, solo con _id funciona
mutation agregarEmpleadoEntidad(
  $busqueda: BuscarEntidadDto!
  $datos: AgregarEmpleadoDto!
) {
  entidadAgregarEmpleado(busqueda: $busqueda, datos: $datos) {
    _id
    cargo
    persona {
      _id
      # nombre
    }
  }
}

mutation borrarEmpleadoEntidad(
  $busqueda: BuscarEntidadDto!
  $busquedaEmpleado: BuscarEmpleadoDto!
) {
  entidadBorrarEmpleado(
    busqueda: $busqueda
    busquedaEmpleado: $busquedaEmpleado
    opciones: {}
  )
}

# BUSCAR STOCKS DE UNA ENTIDAD
query buscarStocks(
  $entidadBusqueda: BuscarEntidadDto!
  $opciones: EntidadOpcionesDto
) {
  entidadBuscarStocks(entidadBusqueda: $entidadBusqueda, opciones: $opciones) {
    producto {
      _id
      nombre
      presentacionBasica
      presentaciones {
        nombre
        cantidad
      }
    }
    lotes {
      vencimiento
      cantidad
      bloque
    }
    fecha
  }
}
