# EMPLEADOS
query buscarEntidadEmpleados($busqueda: BuscarEntidadDto!) {
  entidadBuscar(
    busqueda: $busqueda
    opciones: { populate: ["empleados"], limit: 0 }
  ) {
    _id
    nombre
    empleados {
      _id
      cargo
      persona {
        nombre
        correo
        telefono
      }
    }
  }
}

# Error al poner nombre, solo con _id funciona
mutation agregarEmpleadoEntidad(
  $busqueda: BuscarEntidadDto!
  $datos: AgregarEmpleadoDto!
) {
  entidadAgregarEmpleado(busqueda: $busqueda, datos: $datos) {
    _id
    cargo
    persona {
      _id
      # nombre
    }
  }
}

mutation borrarEmpleadoEntidad(
  $busqueda: BuscarEntidadDto!
  $busquedaEmpleado: BuscarEmpleadoDto!
) {
  entidadBorrarEmpleado(
    busqueda: $busqueda
    busquedaEmpleado: $busquedaEmpleado
    opciones: {}
  )
}

# BUSCAR STOCKS DE UNA ENTIDAD
# query buscarStocks(
#   $entidadBusqueda: BuscarEntidadDto!
#   $opciones: EntidadOpcionesDto
# ) {
#   entidadBuscarStocks(entidadBusqueda: $entidadBusqueda, opciones: $opciones) {
#     producto {
#       _id
#       nombre
#       presentacionBasica
#       presentaciones {
#         nombre
#         cantidad
#       }
#     }
#     lotes {
#       vencimiento
#       cantidad
#       bloque
#     }
#     fecha
#   }
# }

# BUSCAR STOCKS DE UNA ENTIDAD
query buscarStocks($busqueda: BuscarEntidadDto!) {
  entidadBuscar(
    busqueda: $busqueda
    opciones: { limit: 0, populate: ["almacen"] }
  ) {
    almacen {
      producto {
        _id
        nombre
        presentaciones {
          nombre
          cantidad
        }
      }
      cantidadLimite
      lotes {
        vencimiento
        cantidad
        bloque
      }
      inventarios {
        fecha
        lotes {
          vencimiento
          cantidad
          bloque
          presentacion
          cantidadPresentacion
        }
        diferencias {
          vencimiento
          diferencia
        }
      }
    }
    problemas {
      _id
    }
  }
}

# modificar cantidadLimite
mutation modificarCantidadLimite(
  $entidadBusqueda: BuscarEntidadDto!
  $productoBusqueda: BuscarProductoDto!
  $datos: ModificarStockDto!
) {
  entidadModificarStock(
    entidadBusqueda: $entidadBusqueda
    productoBusqueda: $productoBusqueda
    datos: $datos
    opciones: {}
  ) {
    producto {
      _id
    }
    cantidadLimite
  }
}
