query conectar($datos: ConexionDto!) {
  conectar(datos: $datos) {
    token
    persona {
      _id
      nombre
    }
  }
}

query buscarEntidadesConUsuario($opciones: OpcionesDto) {
  entidadesUsuarioConectado(opciones: $opciones) {
    _id
    nombre
    tipo
  }
}

# mandar codigo OTP al correo electronico
query pedirRDC($correo: String!) {
  pedirReinicioDeContrasena(correo: $correo)
}

# cambiar contraseña (OTP, nueva contraseña)
query actuarRDC($token: String!, $contrasena: String!) {
  actuarReinicioDeContrasena(token: $token, contrasena: $contrasena)
}
