query conectar($datos: ConexionDto!) {
  conectar(datos: $datos) {
    token
    persona {
      nombre
    }
  }
}

query buscarEntidadesConUsuario {
  buscarEntidadesConUsuario {
    _id
    nombre
    tipo
  }
}
