mutation crearPersona($datos: CrearPersonaDto!) {
  personaCrear(datos: $datos) {
    _id
    _creado
    contrasena
    nombre
    telefono
    correo
    usuario
  }
}

query buscarPersonas($busqueda: BuscarPersonaDto!) {
  personaBuscar(busqueda: $busqueda, opciones: { populate: true, limit: 0 }) {
    _id
    nombre
    telefono
    correo
  }
}

# query buscarPersona($busqueda: BuscarPersonaDto!) {
#   buscarPersona(busqueda: $busqueda) {
#     _id
#     _creado
#     usuario
#     nombre
#     telefono
#     correo
#   }
# }
