mutation crearPersona($data: CrearPersonaDto!) {
  crearPersona(data: $data) {
    _id
    _creado
    contrasena
    nombre
    telefono
    correo
    usuario
  }
}

query buscarPersonas($busqueda: BuscarPersonaDto!) {
  buscarPersonas(busqueda: $busqueda) {
    _id
    nombre
    telefono
    correo
  }
}

query buscarPersona($busqueda: BuscarPersonaDto!) {
  buscarPersona(busqueda: $busqueda) {
    _id
    _creado
    usuario
    nombre
    telefono
    correo
    usuario
  }
}
