mutation crearUna($data: CrearPersonaDto!) {
  crearUnaPersona(data: $data) {
    _id
    _creado
    contrasena
    nombre
    telefono
    correo
    usuario
  }
}

query buscarVarias($busqueda: BuscarPersonaDto!) {
  buscarVariasPersonas(busqueda: $busqueda) {
    _id
    nombre
    telefono
    correo
  }
}
