# PRODUCTOS
query buscarProductos($busqueda: BuscarProductoDto!) {
  productoBuscar(busqueda: $busqueda, opciones: { populate: true, limit: 0 }) {
    _id
    _creado
    nombre
    descripcion
    tags
    presentacionBasica
    presentaciones {
      _id
      _creado
      nombre
      cantidad
    }
  }
}

mutation crearProducto($datos: CrearProductoDto!) {
  productoCrear(datos: $datos) {
    _id
    _creado
    nombre
    descripcion
    tags
    presentacionBasica
    presentaciones {
      _id
      _creado
      nombre
      cantidad
    }
  }
}

mutation borrarProducto($busqueda: BuscarProductoDto!) {
  productoBorrar(busqueda: $busqueda)
}

# MODIFICAR INFORMACION BASICA
mutation modificarProducto(
  $busqueda: BuscarProductoDto!
  $datos: ModificarProductoDto!
) {
  productoModificar(busqueda: $busqueda, datos: $datos)
}

# MODIFICAR PRESENTACIONES
mutation modificarPresentacion(
  $busqueda: BuscarProductoDto!
  $datos: [ModificarPresentacionDto!]!
) {
  productoModificarPresentacion(
    busqueda: $busqueda
    datos: $datos
    opciones: { limit: 1 }
  )
}
