export const columnsEmpleados = [
  {
    name: 'foto',
    label: 'Imagen',
    align: 'left',
    field: (row: any) => row.foto,
  },
  {
    name: 'nombre',
    required: true,
    label: 'Nombre(s)',
    align: 'left',
    field: (row: any) => row.nombre,
    sortable: true,
  },
  // {
  //   name: 'correo',
  //   required: true,
  //   label: 'Correo',
  //   align: 'left',
  //   field: (row: any) => row.correo,
  //   sortable: true,
  // },
  // {
  //   name: 'telefono',
  //   required: true,
  //   label: 'Telefono',
  //   align: 'left',
  //   field: (row: any) => row.telefono,
  //   sortable: true,
  // },
  {
    name: 'cargo',
    required: true,
    label: 'Cargo',
    align: 'left',
    field: (row: any) => row.cargo,
    sortable: true,
  },
  {
    name: 'Permisos',
    required: true,
    label: 'Permisos',
    align: 'left',
    field: (row: any) => row.permisos.join(', '),
    sortable: true,
  },
  {
    name: 'actions',
    label: 'Acciones',
    align: 'right',
  },
];

export const columnsOfertas = [
  // {
  //   name: 'creado',
  //   label: 'Creado',
  //   align: 'left',
  //   field: (row: any) => row._creado,
  // },
  {
    name: 'imagen',
    label: 'Imagen',
    align: 'left',
    field: (row: any) => row.imagen,
  },
  {
    name: 'modificado',
    label: 'Modificado',
    align: 'left',
    field: (row: any) => row._modificado,
    sortable: true,
  },
  {
    name: 'nombre',
    label: 'Nombre',
    align: 'left',
    field: (row: any) => row.nombre,
    sortable: true,
  },
  {
    name: 'ingredientes',
    required: true,
    label: 'Ingredientes',
    align: 'left',
    field: (row: any) => row.ingredientes,
  },
  // {
  //   name: 'preparados',
  //   required: true,
  //   label: 'Preparados',
  //   align: 'left',
  //   field: (row: any) => row.preparados.map((p: any) => p),
  //   sortable: true,
  // },
  {
    name: 'catalogo',
    required: true,
    label: 'Catalogo',
    align: 'left',
    field: (row: any) => row.catalogo,
    sortable: true,
  },
  {
    name: 'precio',
    required: true,
    label: 'precio',
    align: 'left',
    field: (row: any) => row.precio,
    sortable: true,
  },
  {
    name: 'actions',
    label: 'Acciones',
    align: 'right',
  },
];

export const columnsProductos = [
  {
    name: 'imagen',
    label: 'Imagen',
    align: 'left',
    field: (row: any) => row.imagen,
  },
  {
    name: 'modificado',
    label: 'Modificado',
    align: 'left',
    field: (row: any) => row._modificado,
    sortable: true,
  },
  {
    name: 'nombre',
    required: true,
    label: 'Nombre(s)',
    align: 'left',
    field: (row: any) => row.nombre,
    sortable: true,
  },
  {
    name: 'medida',
    required: true,
    label: 'Unidad Medida',
    align: 'left',
    field: (row: any) => row.medida.nombre,
    sortable: true,
  },
  {
    name: 'categoria',
    required: true,
    label: 'categoria',
    align: 'left',
    field: (row: any) => row.categoria.nombre,
    sortable: true,
  },
  {
    name: 'actions',
    label: 'Acciones',
    align: 'right',
  },
];

export const stockProducts = [
  // {
  //   name: 'foto',
  //   label: 'Imagen',
  //   align: 'left',
  //   field: (row: any) => row.foto,
  // },
  {
    name: 'producto',
    required: true,
    label: 'Producto',
    align: 'left',
    field: (row: any) => row.producto.nombre,
    sortable: true,
  },
  {
    name: 'presentacionBasica',
    required: true,
    label: 'P. basica',
    align: 'left',
    field: (row: any) => row.producto.presentacionBasica,
    sortable: true,
  },
  {
    name: 'presentaciones',
    required: true,
    label: 'Presentaciones',
    align: 'left',
    field: (row: any) => row.presentaciones.map((p: any) => p.nombre),
    sortable: true,
  },
  {
    name: 'lotes',
    required: true,
    label: 'Lotes',
    align: 'left',
    field: (row: any) => row.lotes,
    sortable: true,
  },
  {
    name: 'cantidad',
    required: true,
    label: 'Cantidad Total',
    align: 'left',
    field: (row: any) => row.cantidad,
    sortable: true,
  },
  {
    name: 'cantidadMinima',
    required: true,
    label: 'Cantidad Minima',
    align: 'left',
    field: (row: any) => row.cantidadMinima,
    sortable: true,
  },
  {
    name: 'actions',
    label: 'Acciones',
    align: 'right',
  },
];

export const detallePedido = [
  {
    name: 'oferta',
    required: true,
    label: 'Oferta',
    align: 'left',
    field: (row: any) => row.oferta.nombre,
    sortable: true,
  },
  {
    name: 'precio',
    required: true,
    label: 'Precio U.',
    align: 'center',
    field: (row: any) => row.oferta.precio,
    sortable: true,
  },
  {
    name: 'cantidad',
    required: true,
    label: 'Cantidad',
    align: 'center',
    field: (row: any) => row.cantidad,
    sortable: true,
  },
  {
    name: 'precioTotal',
    required: true,
    label: 'Precio Total',
    align: 'right',
    field: (row: any) => row.cantidad * row.oferta.precio,
    sortable: true,
  },
  {
    name: 'actions',
    label: 'Acciones',
    align: 'right',
  },
];

export const detallePedidoPunto = [
  {
    name: 'oferta',
    required: true,
    label: 'Oferta',
    align: 'left',
    field: (row: any) => row.oferta.nombre,
    sortable: true,
  },
  {
    name: 'precio',
    required: true,
    label: 'Precio U.',
    align: 'center',
    field: (row: any) => row.oferta.precio,
    sortable: true,
  },
  {
    name: 'cantidad',
    required: true,
    label: 'Cantidad',
    align: 'center',
    field: (row: any) => row.cantidad,
    sortable: true,
  },
  {
    name: 'precioTotal',
    required: true,
    label: 'Precio Total',
    align: 'right',
    field: (row: any) => row.cantidad * row.oferta.precio,
    sortable: true,
  },
];

export const detallePedidoAccion = [
  {
    name: 'oferta',
    required: true,
    label: 'Oferta',
    align: 'left',
    field: (row: any) => row.oferta.nombre,
    sortable: true,
  },
  {
    name: 'precio',
    required: true,
    label: 'Precio U.',
    align: 'center',
    field: (row: any) => row.oferta.precio,
    sortable: true,
  },
  {
    name: 'cantidad',
    required: true,
    label: 'Cantidad',
    align: 'center',
    field: (row: any) => row.cantidad,
    sortable: true,
  },
  {
    name: 'precioTotal',
    required: true,
    label: 'Precio Total',
    align: 'right',
    field: (row: any) => row.cantidad * row.oferta.precio,
    sortable: true,
  },
  {
    name: 'actions',
    label: 'Acciones',
    align: 'right',
  },
];
export const detallePedidoAlmacen = [
  {
    name: 'oferta',
    required: true,
    label: 'Oferta',
    align: 'left',
    field: (row: any) => row.oferta.nombre,
    sortable: true,
  },
  {
    name: 'cantidad',
    required: true,
    label: 'Cantidad',
    align: 'center',
    field: (row: any) => row.cantidad,
    sortable: true,
  },
  {
    name: 'actions',
    label: 'Acciones',
    align: 'right',
  },
];

export const pedidoGlobal = [
  {
    name: 'nombre',
    required: true,
    label: 'Nombre(s)',
    align: 'left',
    field: (row: any) => row.oferta.nombre,
    sortable: true,
  },
  {
    name: 'pedido',
    required: true,
    label: 'Pedido',
    align: 'center',
    field: (row: any) => row.cantidad,
    sortable: true,
  },
  {
    name: 'cantidadPedido',
    required: true,
    label: 'Cantidad Pedido',
    align: 'center',
    field: (row: any) =>
      row.cantidad * row.oferta.cantidad + `(${row.presentacionBasica})`,
    sortable: true,
  },
  {
    name: 'cantidadStock',
    required: true,
    label: 'Cantidad Stock',
    align: 'center',
    field: (row: any) => row.stockEntidad + `(${row.presentacionBasica})`,
    sortable: true,
  },
  {
    name: 'diferencia',
    required: true,
    label: 'Diferencia',
    align: 'right',
    field: (row: any) => row.stockEntidad - row.cantidad,
    sortable: true,
  },
  {
    name: 'actions',
    label: 'Acciones',
    align: 'right',
  },
];

export const tesoreriaCobrar = [
  {
    name: 'entidad',
    required: true,
    label: 'Cliente',
    align: 'left',
    field: (row: any) => row.entidad,
    sortable: true,
  },
  {
    name: 'pedidosAnteriores',
    required: true,
    label: 'Semanas Anteriores',
    align: 'center',
    field: (row: any) => row.pedidosAnteriores,
    sortable: true,
  },
  {
    name: 'pedidosSemanaActual',
    required: true,
    label: 'Ultima Semana',
    align: 'center',
    field: (row: any) => row.pedidosSemanaActual,
    sortable: true,
  },
  {
    name: 'total',
    required: true,
    label: 'Total',
    align: 'right',
    sortable: true,
  },
  {
    name: 'actions',
    label: 'Acciones',
    align: 'right',
  },
];

export const tesoreriaPendiente = [
  {
    name: 'entidad',
    required: true,
    label: 'Cliente',
    align: 'left',
    field: (row: any) => row.entidad,
    sortable: true,
  },
  {
    name: '_creado',
    required: true,
    label: 'Fecha',
    align: 'center',
    field: (row: any) => row._creado,
    sortable: true,
  },
  {
    name: 'monto',
    required: true,
    label: 'Monto',
    align: 'center',
    field: (row: any) => row.monto,
    sortable: true,
  },
  {
    name: 'tipo',
    required: true,
    label: 'Tipo',
    align: 'center',
    field: (row: any) => row.tipo,
    sortable: true,
  },
  {
    name: 'actions',
    label: 'Acciones',
    align: 'right',
  },
];

export const marcas = [
  {
    name: 'imagen',
    label: 'Imagen',
    align: 'left',
    field: (row: any) => row.imagen?.cloudinaryUrl,
  },
  {
    name: 'marca',
    required: true,
    label: 'Marca',
    align: 'left',
    field: (row: any) => row.marca?.nombre,
    sortable: true,
  },
  {
    name: 'min',
    required: true,
    label: 'Min',
    align: 'center',
    field: (row: any) => row.cantidadMin,
    sortable: true,
  },
  {
    name: 'max',
    required: true,
    label: 'Max',
    align: 'center',
    field: (row: any) => row.cantidadMax,
    sortable: true,
  },
  {
    name: 'actions',
    label: 'Acciones',
    align: 'right',
  },
];

export const empaques = [
  {
    name: 'nombre',
    required: true,
    label: 'Nombre',
    align: 'center',
    field: (row: any) => row.nombre,
    sortable: true,
  },
  {
    name: 'abreviacion',
    required: true,
    label: 'Abreviacion',
    align: 'center',
    field: (row: any) => row.abreviacion,
    sortable: true,
  },
  {
    name: 'cantidad',
    required: true,
    label: 'Cantidad',
    align: 'center',
    field: (row: any) => row.cantidad,
    sortable: true,
  },
  {
    name: 'marca',
    required: true,
    label: 'Marca',
    align: 'left',
    field: (row: any) => row.marca?.nombre,
    sortable: true,
  },
  {
    name: 'actions',
    label: 'Acciones',
    align: 'right',
  },
];

export const proveedores = [
  {
    name: 'proveedor',
    required: true,
    label: 'Proveedor',
    align: 'left',
    field: (row: any) => row.nombre,
    sortable: true,
  },
  {
    name: 'marca',
    required: true,
    label: 'Marca',
    align: 'center',
    field: (row: any) => row.servicios[0].marca.nombre,
    sortable: true,
  },
  {
    name: 'identificativo',
    required: true,
    label: 'Identificativo',
    align: 'center',
    field: (row: any) => row.servicios[0].identificativo,
    sortable: true,
  },
  {
    name: 'precioConFactura',
    required: true,
    label: 'Precio C/F',
    align: 'center',
    field: (row: any) => row.servicios[0].precioConFactura + 'Bs',
    sortable: true,
  },
  {
    name: 'precioSinFactura',
    required: true,
    label: 'Precio S/F',
    align: 'center',
    field: (row: any) => row.servicios[0].precioSinFactura + 'Bs',
    sortable: true,
  },
  {
    name: 'actions',
    label: 'Acciones',
    align: 'right',
  },
];
