export const columnsEmpleados = [
  {
    name: 'foto',
    label: 'Imagen',
    align: 'left',
    field: (row: any) => row.foto,
  },
  {
    name: 'nombre',
    required: true,
    label: 'Nombre(s)',
    align: 'left',
    field: (row: any) => row.nombre,
    sortable: true,
  },
  {
    name: 'correo',
    required: true,
    label: 'Correo',
    align: 'left',
    field: (row: any) => row.correo,
    sortable: true,
  },
  {
    name: 'telefono',
    required: true,
    label: 'Telefono',
    align: 'left',
    field: (row: any) => row.telefono,
    sortable: true,
  },
  {
    name: 'rol',
    required: true,
    label: 'Rol',
    align: 'left',
    field: (row: any) => row.cargo,
    sortable: true,
  },
  {
    name: 'actions',
    label: 'Acciones',
    align: 'right',
  },
];

export const columnsOfertas = [
  {
    name: 'nombre',
    label: 'Nombre',
    align: 'left',
    field: (row: any) => row.nombre,
  },
  {
    name: 'ingredientes',
    required: true,
    label: 'Ingredientes',
    align: 'left',
    field: (row: any) => row.ingredientes,
    sortable: true,
  },
  {
    name: 'preparados',
    required: true,
    label: 'Preparados',
    align: 'left',
    field: (row: any) => row.preparados.map((p: any) => p),
    sortable: true,
  },
  {
    name: 'grupos',
    required: true,
    label: 'grupos',
    align: 'left',
    field: (row: any) => row.grupos,
    sortable: true,
  },
  {
    name: 'precio',
    required: true,
    label: 'precio',
    align: 'left',
    field: (row: any) => row.precio,
    sortable: true,
  },
  {
    name: 'ocultar',
    required: true,
    label: 'Desabilitar',
    align: 'left',
    field: (row: any) => row.ocultar,
    sortable: true,
  },
  {
    name: 'actions',
    label: 'Acciones',
    align: 'right',
  },
];

export const columnsProductos = [
  {
    name: 'nombre',
    required: true,
    label: 'Nombre(s)',
    align: 'left',
    field: (row: any) => row.nombre,
    sortable: true,
  },
  {
    name: 'comentario',
    required: true,
    label: 'Comentario',
    align: 'left',
    field: (row: any) => row.comentario,
    sortable: true,
  },
  {
    name: 'presentacionBasica',
    required: true,
    label: 'U.M',
    align: 'left',
    field: (row: any) => row.presentacionBasica,
    sortable: true,
  },
  {
    name: 'presentaciones',
    required: true,
    label: 'presentaciones',
    align: 'left',
    field: (row: any) => row.presentaciones.map((p: any) => p.nombre),
    sortable: true,
  },
  {
    name: 'categoria',
    required: true,
    label: 'categoria',
    align: 'left',
    field: (row: any) => row.categoria.nombre,
    sortable: true,
  },
  {
    name: 'actions',
    label: 'Acciones',
    align: 'right',
  },
];

export const stockProducts = [
  {
    name: 'foto',
    label: 'Imagen',
    align: 'left',
    field: (row: any) => row.foto,
  },
  {
    name: 'producto',
    required: true,
    label: 'Producto',
    align: 'left',
    field: (row: any) => row.producto.nombre,
    sortable: true,
  },
  {
    name: 'presentaciones',
    required: true,
    label: 'Presentaciones',
    align: 'left',
    field: (row: any) => row.presentaciones.map((p: any) => p.nombre),
    sortable: true,
  },
  {
    name: 'lotes',
    required: true,
    label: 'Lotes',
    align: 'left',
    field: (row: any) => row.lotes,
    sortable: true,
  },
  {
    name: 'cantidad',
    required: true,
    label: 'Cantidad Total',
    align: 'left',
    field: (row: any) => row.cantidad,
    sortable: true,
  },
  {
    name: 'cantidadMinima',
    required: true,
    label: 'Cantidad Minima',
    align: 'left',
    field: (row: any) => row.cantidadMinima,
    sortable: true,
  },
  {
    name: 'actions',
    label: 'Acciones',
    align: 'right',
  },
];

export const detallePedido = [
  {
    name: 'oferta',
    required: true,
    label: 'Oferta',
    align: 'left',
    field: (row: any) => row.oferta.nombre,
    sortable: true,
  },
  {
    name: 'precio',
    required: true,
    label: 'Precio U.',
    align: 'center',
    field: (row: any) => row.oferta.precio,
    sortable: true,
  },
  {
    name: 'cantidad',
    required: true,
    label: 'Cantidad',
    align: 'center',
    field: (row: any) => row.cantidad,
    sortable: true,
  },
  {
    name: 'precioTotal',
    required: true,
    label: 'Precio Total',
    align: 'right',
    field: (row: any) => row.cantidad * row.oferta.precio,
    sortable: true,
  },
];
