# CREAR PEDIDO
mutation crearPedido(
  $datos: [CrearPedidoDto!]!
  $opciones: CrearOpciones = {}
) {
  crearPedidos(datos: $datos, opciones: $opciones) {
    _id
  }
}

# INICIAR PEDIDO DESDE
mutation iniciarPedido($datos: CrearPedidoDto!, $opciones: CrearOpciones = {}) {
  iniciarPedido(datos: $datos, opciones: $opciones) {
    _id
    estado {
      estado
    }
    items {
      oferta {
        nombre
      }
      cantidad
      estado {
        estado
      }
    }
  }
}

# cambia de estado los items de un pedido
mutation cambiarEstadoItems(
  $busqueda: BuscarPedidoDto = {}
  $itemIds: [ID!] = []
  $estado: CrearItemEstadoDto!
  $opciones: BuscarOpciones = {}
) {
  cambiarEstadoItems(
    busqueda: $busqueda
    itemIds: $itemIds
    estado: $estado
    opciones: $opciones
  ) {
    _id
  }
}

# Busca todos los pedidos\
query buscarPedidos(
  $busqueda: BuscarPedidoDto = {}
  $opciones: BuscarOpciones = {}
  $filtro: BuscarPedidoDto = {}
) {
  buscarPedidos(busqueda: $busqueda, opciones: $opciones, filtro: $filtro) {
    _id
    _creado
    comprador {
      nombre
      _id
      ruta
      orden
    }
    vendedor {
      nombre
      _id
      ruta
      orden
    }
    estado {
      estado
      _creado
      persona {
        nombre
        apellido
        telefono
      }
    }
    items {
      _id
      oferta {
        nombre
        _id
        ingredientes {
          tipo
          producto {
            nombre
          }
          cantidad
        }
        precioConFactura
        precioSinFactura
        preciosPorMayor {
          cantidadMin
          precioConFactura
          precioSinFactura
        }
      }
      cantidad
      estado {
        _creado
        estado
        valor
        comentario
      }
    }
  }
}

# Lee el estado de un pedido
query leerEstadoPedido(
  $busqueda: BuscarPedidoDto = {}
  $opciones: BuscarOpciones = {}
) {
  leerEstadoPedido(busqueda: $busqueda, opciones: $opciones)
}

query entidadLeerMenu(
  $busqueda: BuscarEntidadDto!
  $busquedaMenu: BuscarMenuDto!
  $opciones: BuscarOpciones = {}
) {
  entidadLeerMenu(
    busqueda: $busqueda
    busquedaMenu: $busquedaMenu
    opciones: $opciones
  ) {
    _id
    nombre
    hijas {
      _id
      nombre
      ofertas {
        nombre
      }
      hijas {
        _id
        nombre
        ofertas {
          _id
          nombre
        }
      }
    }
    ofertas {
      _id
      nombre
      ingredientes {
        _id
      }
    }
  }
}
