# BUSCAR ENTIDADES TIPO PROVEEDOR
query buscarEntidadesProveedor(
  $busqueda: BuscarEntidadDto = {}
  $opciones: BuscarOpciones = {}
  $filtro: BuscarEntidadDto = {}
) {
  buscarEntidades(busqueda: $busqueda, opciones: $opciones, filtro: $filtro) {
    _id
    nombre
    tipo
  }
}

# CREAR UNA ENTIDAD PROVEEDOR
mutation crearEntidadProveedor(
  $datos: [CrearEntidadDto!]!
  $opciones: CrearOpciones = {}
) {
  crearEntidades(datos: $datos, opciones: $opciones) {
    _id
    nombre
    tipo
  }
}

# ENTIDADES SERVICIOS
mutation ModificarEntidadesServicio(
  $busqueda: BuscarEntidadDto!
  $datos: ModificarEntidadDto!
  $opciones: ModificarOpciones = {}
) {
  modificarEntidades(busqueda: $busqueda, datos: $datos, opciones: $opciones) {
    _id
    nombre
    tipo
    servicios {
      _id
      identificativo
      producto {
        _id
        nombre
      }
      marca {
        _id
        nombre
      }
      precioConFactura
      precioSinFactura
      preciosPorMayor {
        _id
        cantidadMin
        precioSinFactura
        precioConFactura
      }
    }
  }
}

# BUSCAR ENTIDADES TIPO PROVEEDOR DE UN PRODUCTO
query buscarEntidadesServicios(
  $busqueda: BuscarEntidadDto = {}
  $opciones: BuscarOpciones = {}
  $filtro: BuscarEntidadDto = {}
) {
  buscarEntidades(busqueda: $busqueda, opciones: $opciones, filtro: $filtro) {
    _id
    nombre
    tipo
    servicios {
      _id
      identificativo
      producto {
        _id
        nombre
      }
      marca {
        _id
        nombre
      }
      precioConFactura
      precioSinFactura
      preciosPorMayor {
        _id
        cantidadMin
        precioSinFactura
        precioConFactura
      }
    }
  }
}
