query almacenBuscarEntidades(
  $busqueda: BuscarEntidadDto = {}
  $opciones: BuscarOpciones = {}
  $filtro: BuscarEntidadDto = {}
) {
  buscarEntidades(busqueda: $busqueda, opciones: $opciones, filtro: $filtro) {
    _id
    nombre
    tipo
  }
}

mutation almacenModificarEntidades(
  $busqueda: BuscarEntidadDto!
  $datos: ModificarEntidadDto!
  $opciones: ModificarOpciones = {}
) {
  modificarEntidades(busqueda: $busqueda, datos: $datos, opciones: $opciones) {
    _id
  }
}

mutation almacenCrearEntidades(
  $datos: [CrearEntidadDto!]!
  $opciones: CrearOpciones = {}
) {
  crearEntidades(datos: $datos, opciones: $opciones) {
    _id
  }
}
