query stockBuscarEntidad(
  $busqueda: BuscarEntidadDto = {}
  $opciones: BuscarOpciones = {}
  $filtro: BuscarEntidadDto = {}
) {
  buscarEntidades(busqueda: $busqueda, opciones: $opciones, filtro: $filtro) {
    almacen {
      _id
      producto {
        _id
        nombre
        puedeVencer
        vencimientoLimite
        categoria {
          _id
          nombre
        }
        imagen {
          cloudinaryUrl
        }
        medida {
          abreviacion
        }
        variedades {
          _id
          marca {
            _id
            nombre
          }
          inventarioLimite
          cantidadLimite
          cantidadMaxPedido
          imagen {
            archivoLocal
            cloudinaryUrl
          }
        }
      }
      lotes {
        vencimiento
        cantidad
        marca {
          _id
          nombre
        }
        bloque {
          _id
          nombre
        }
      }
    }
  }
}

mutation stockModificarEntidad(
  $busqueda: BuscarEntidadDto!
  $datos: ModificarEntidadDto!
  $opciones: ModificarOpciones = {}
) {
  modificarEntidades(busqueda: $busqueda, datos: $datos, opciones: $opciones) {
    almacen {
      producto {
        _id
        nombre
        puedeVencer
        vencimientoLimite
      }
      lotes {
        vencimiento
        cantidad
        marca {
          _id
          nombre
        }
        bloque {
          _id
          nombre
        }
      }
    }
  }
}
